### ISSUE TITLE
 Доработка

### ISSUE THREAD

**Issue by YlabCourse** [aSel1x/ylab-fastapi-postgresql#1]
Тесты падают

сколонируй проект, запусти по инструкции, и убедись что все тесты проходят.
Прошло 26 тесто упало 7 и проекто тоде упал, остальные тесты тоже не прошли

**Comment by aSel1x** [comment]
[menu app - My Workspace.pdf](https://github.com/aSel1x/ylab-fastapi-postgresql/files/14039876/menu.app.-.My.Workspace.pdf)

Надеялся своими тестами, но не вышло. Чутка допилил, теперь и ваши проходят.
